sonata_admin:
    title: 'Ebay admin'
    templates:
        user_block: 'admin/user_block.html.twig'
    search: false
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    options:
        legacy_twig_text_extension: false
    assets:
        extra_stylesheets:
            - admin/extra_style.css
        extra_javascripts:
            #- https://cdn.ckeditor.com/ckeditor5/20.0.0/classic/ckeditor.js
            #- admin/extra_scripts.js

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
